// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZK.Persistence;

#nullable disable

namespace ZK.Persistence.Migrations
{
    [DbContext(typeof(ZKDbContext))]
    [Migration("20250828001242_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ZK.Domain.Entities.Vehicles.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleId"));

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MakeId")
                        .HasColumnType("int");

                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<bool>("Sold")
                        .HasColumnType("bit");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("VehicleId");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("VehicleId"));

                    b.HasIndex("MakeId");

                    b.HasIndex("ModelId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Vehicles", (string)null);

                    b.HasData(
                        new
                        {
                            VehicleId = 1,
                            Color = "White",
                            Description = "2025 Toyota Camry in white color",
                            MakeId = 1,
                            ModelId = 1,
                            Price = 25000.00m,
                            Slug = "camry-2025-1",
                            Sold = false,
                            Year = 2025
                        },
                        new
                        {
                            VehicleId = 2,
                            Color = "Blue",
                            Description = "2024 Toyota Corolla in blue color",
                            MakeId = 1,
                            ModelId = 2,
                            Price = 20000.00m,
                            Slug = "corolla-2024-2",
                            Sold = true,
                            Year = 2024
                        },
                        new
                        {
                            VehicleId = 3,
                            Color = "Red",
                            Description = "2023 Ford Focus in red",
                            MakeId = 2,
                            ModelId = 4,
                            Price = 22000.00m,
                            Slug = "focus-2023-3",
                            Sold = false,
                            Year = 2023
                        },
                        new
                        {
                            VehicleId = 4,
                            Color = "Black",
                            Description = "2024 Ford Mustang GT",
                            MakeId = 2,
                            ModelId = 5,
                            Price = 35000.00m,
                            Slug = "mustang-2024-4",
                            Sold = false,
                            Year = 2024
                        },
                        new
                        {
                            VehicleId = 5,
                            Color = "Gray",
                            Description = "2023 Honda Civic in gray color",
                            MakeId = 3,
                            ModelId = 6,
                            Price = 21000.00m,
                            Slug = "civic-2023-5",
                            Sold = true,
                            Year = 2023
                        });
                });

            modelBuilder.Entity("ZK.Domain.Entities.Vehicles.VehicleMake", b =>
                {
                    b.Property<int>("VehicleMakeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleMakeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("VehicleMakeId");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("VehicleMakeId"));

                    b.ToTable("VehicleMakes", (string)null);

                    b.HasData(
                        new
                        {
                            VehicleMakeId = 1,
                            Name = "Toyota"
                        },
                        new
                        {
                            VehicleMakeId = 2,
                            Name = "Ford"
                        },
                        new
                        {
                            VehicleMakeId = 3,
                            Name = "Honda"
                        },
                        new
                        {
                            VehicleMakeId = 4,
                            Name = "Chevrolet"
                        });
                });

            modelBuilder.Entity("ZK.Domain.Entities.Vehicles.VehicleModel", b =>
                {
                    b.Property<int>("VehicleModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleModelId"));

                    b.Property<int>("MakeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("VehicleModelId");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("VehicleModelId"));

                    b.HasIndex("MakeId");

                    b.ToTable("VehicleModels", (string)null);

                    b.HasData(
                        new
                        {
                            VehicleModelId = 1,
                            MakeId = 1,
                            Name = "Camry"
                        },
                        new
                        {
                            VehicleModelId = 2,
                            MakeId = 1,
                            Name = "Corolla"
                        },
                        new
                        {
                            VehicleModelId = 3,
                            MakeId = 1,
                            Name = "RAV4"
                        },
                        new
                        {
                            VehicleModelId = 4,
                            MakeId = 2,
                            Name = "F-150"
                        },
                        new
                        {
                            VehicleModelId = 5,
                            MakeId = 2,
                            Name = "Mustang"
                        },
                        new
                        {
                            VehicleModelId = 6,
                            MakeId = 3,
                            Name = "Civic"
                        },
                        new
                        {
                            VehicleModelId = 7,
                            MakeId = 3,
                            Name = "Accord"
                        },
                        new
                        {
                            VehicleModelId = 8,
                            MakeId = 4,
                            Name = "Silverado"
                        },
                        new
                        {
                            VehicleModelId = 9,
                            MakeId = 4,
                            Name = "Malibu"
                        });
                });

            modelBuilder.Entity("ZK.Domain.Entities.Vehicles.Vehicle", b =>
                {
                    b.HasOne("ZK.Domain.Entities.Vehicles.VehicleMake", "Make")
                        .WithMany("Vehicles")
                        .HasForeignKey("MakeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ZK.Domain.Entities.Vehicles.VehicleModel", "Model")
                        .WithMany("Vehicles")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Make");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("ZK.Domain.Entities.Vehicles.VehicleModel", b =>
                {
                    b.HasOne("ZK.Domain.Entities.Vehicles.VehicleMake", "Make")
                        .WithMany("VehicleModels")
                        .HasForeignKey("MakeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Make");
                });

            modelBuilder.Entity("ZK.Domain.Entities.Vehicles.VehicleMake", b =>
                {
                    b.Navigation("VehicleModels");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("ZK.Domain.Entities.Vehicles.VehicleModel", b =>
                {
                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
