// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZK.Persistence;

#nullable disable

namespace ZK.Persistence.Migrations
{
    [DbContext(typeof(ZKDbContext))]
    partial class ZKDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ZK.Domain.Entities.Sales.SaleHistory", b =>
                {
                    b.Property<int>("SaleHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaleHistoryId"));

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CustomerPhoneNo")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("SaleDateTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SalePrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("SaleHistoryId");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("SaleHistoryId"));

                    b.HasIndex("VehicleId")
                        .IsUnique();

                    b.ToTable("SaleHistories", (string)null);
                });

            modelBuilder.Entity("ZK.Domain.Entities.Users.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("RoleId");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("RoleId"));

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("ZK.Domain.Entities.Users.RoleClaim", b =>
                {
                    b.Property<int>("RoleClaimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleClaimId"));

                    b.Property<string>("ClaimType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ClaimValue")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("RoleClaimId");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("RoleClaimId"), false);

                    b.HasIndex("ClaimValue")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("RoleId"));

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("ZK.Domain.Entities.Users.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("UserId"), false);

                    b.HasIndex("UserName")
                        .IsUnique();

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("UserName"));

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("ZK.Domain.Entities.Users.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("ZK.Domain.Entities.Vehicles.BodyType", b =>
                {
                    b.Property<int>("BodyTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BodyTypeId"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("BodyTypeId");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("BodyTypeId"));

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("BodyTypes", (string)null);

                    b.HasData(
                        new
                        {
                            BodyTypeId = 1,
                            Description = "A passenger car in a three-box configuration with separate compartments for engine, passenger, and cargo.",
                            Name = "Sedan"
                        },
                        new
                        {
                            BodyTypeId = 2,
                            Description = "Vehicle with an open cargo area and passenger cab, used for hauling.",
                            Name = "Pickup Truck"
                        },
                        new
                        {
                            BodyTypeId = 3,
                            Description = "Sport Utility Vehicle combining off-road capability with passenger comfort.",
                            Name = "SUV"
                        },
                        new
                        {
                            BodyTypeId = 4,
                            Description = "A two-door car with a fixed roof and sporty design.",
                            Name = "Coupe"
                        },
                        new
                        {
                            BodyTypeId = 5,
                            Description = "Compact car with a rear door that swings upward to provide access to cargo area.",
                            Name = "Hatchback"
                        },
                        new
                        {
                            BodyTypeId = 6,
                            Description = "Car with a roof structure that can be 'converted' to allow open-air or enclosed driving.",
                            Name = "Convertible"
                        },
                        new
                        {
                            BodyTypeId = 7,
                            Description = "A van designed for personal use, especially for families.",
                            Name = "Minivan"
                        },
                        new
                        {
                            BodyTypeId = 8,
                            Description = "A car with an extended rear cargo area, accessed via a rear door or hatch.",
                            Name = "Station Wagon"
                        },
                        new
                        {
                            BodyTypeId = 9,
                            Description = "A larger vehicle used for transporting goods or groups of people.",
                            Name = "Van"
                        },
                        new
                        {
                            BodyTypeId = 10,
                            Description = "Vehicle built on a car platform combining features of a hatchback and SUV.",
                            Name = "Crossover"
                        });
                });

            modelBuilder.Entity("ZK.Domain.Entities.Vehicles.Drivetrain", b =>
                {
                    b.Property<int>("DrivetrainId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DrivetrainId"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DrivetrainId");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("DrivetrainId"));

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Drivetrains", (string)null);

                    b.HasData(
                        new
                        {
                            DrivetrainId = 1,
                            Description = "Power delivered to the front wheels, typical for fuel-efficient vehicles.",
                            Name = "Front-Wheel Drive (FWD)"
                        },
                        new
                        {
                            DrivetrainId = 2,
                            Description = "Power delivered to the rear wheels, preferred for performance and towing.",
                            Name = "Rear-Wheel Drive (RWD)"
                        },
                        new
                        {
                            DrivetrainId = 3,
                            Description = "Power automatically distributed to all wheels for better traction.",
                            Name = "All-Wheel Drive (AWD)"
                        },
                        new
                        {
                            DrivetrainId = 4,
                            Description = "Driver-selectable power distributed to all four wheels, for off-road driving.",
                            Name = "Four-Wheel Drive (4WD)"
                        });
                });

            modelBuilder.Entity("ZK.Domain.Entities.Vehicles.Engine", b =>
                {
                    b.Property<int>("EngineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EngineId"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EngineId");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("EngineId"));

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Engines", (string)null);

                    b.HasData(
                        new
                        {
                            EngineId = 1,
                            Description = "Reliable 2.5 liter inline 4-cylinder engine, suitable for everyday driving.",
                            Name = "2.5L Inline 4 Cylinder"
                        },
                        new
                        {
                            EngineId = 2,
                            Description = "Powerful 3.5 liter V6 engine for enhanced performance.",
                            Name = "3.5L V6"
                        },
                        new
                        {
                            EngineId = 3,
                            Description = "Turbocharged 2.0 liter inline 4-cylinder engine with improved acceleration.",
                            Name = "2.0L Turbo Inline 4"
                        },
                        new
                        {
                            EngineId = 4,
                            Description = "Large 5.3 liter V8 engine, commonly used in trucks and SUVs for towing.",
                            Name = "5.3L V8"
                        },
                        new
                        {
                            EngineId = 5,
                            Description = "High-performance 5.0 liter V8 engine for sports vehicles.",
                            Name = "5.0L V8"
                        },
                        new
                        {
                            EngineId = 6,
                            Description = "Fuel-efficient 1.5 liter turbocharged inline 4-cylinder engine.",
                            Name = "1.5L Turbo Inline 4"
                        });
                });

            modelBuilder.Entity("ZK.Domain.Entities.Vehicles.FuelType", b =>
                {
                    b.Property<int>("FuelTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FuelTypeId"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("FuelTypeId");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("FuelTypeId"));

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("FuelTypes", (string)null);

                    b.HasData(
                        new
                        {
                            FuelTypeId = 1,
                            Description = "Standard gasoline fuel used in most combustion engines.",
                            Name = "Gasoline"
                        },
                        new
                        {
                            FuelTypeId = 2,
                            Description = "Diesel fuel offering higher efficiency and torque for heavy-duty vehicles.",
                            Name = "Diesel"
                        },
                        new
                        {
                            FuelTypeId = 3,
                            Description = "Combination of gasoline engine and electric motor for improved fuel economy.",
                            Name = "Hybrid"
                        },
                        new
                        {
                            FuelTypeId = 4,
                            Description = "Fully electric powertrain using battery stored energy.",
                            Name = "Electric"
                        });
                });

            modelBuilder.Entity("ZK.Domain.Entities.Vehicles.Transmission", b =>
                {
                    b.Property<int>("TransmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransmissionId"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TransmissionId");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("TransmissionId"));

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Transmissions", (string)null);

                    b.HasData(
                        new
                        {
                            TransmissionId = 1,
                            Description = "Requires driver to manually change gears using clutch and gear lever.",
                            Name = "Manual"
                        },
                        new
                        {
                            TransmissionId = 2,
                            Description = "Automatically changes gears without driver input for convenience.",
                            Name = "Automatic"
                        },
                        new
                        {
                            TransmissionId = 3,
                            Description = "Delivers smooth acceleration with a seamless range of gear ratios.",
                            Name = "Continuously Variable Transmission (CVT)"
                        },
                        new
                        {
                            TransmissionId = 4,
                            Description = "Offers quick, efficient gear changes with two separate clutches.",
                            Name = "Dual-Clutch Automatic"
                        },
                        new
                        {
                            TransmissionId = 5,
                            Description = "A manual transmission with automated clutch and gear shifts.",
                            Name = "Automated Manual (AMT)"
                        });
                });

            modelBuilder.Entity("ZK.Domain.Entities.Vehicles.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleId"));

                    b.Property<DateTime>("AddedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("VehicleId");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("VehicleId"));

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("StatusId");

                    b.ToTable("Vehicles", (string)null);
                });

            modelBuilder.Entity("ZK.Domain.Entities.Vehicles.VehicleBasicIdentification", b =>
                {
                    b.Property<int>("VehicleBasicIdentificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleBasicIdentificationId"));

                    b.Property<int>("BodyTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExteriorColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Features")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InteriorColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MakeId")
                        .HasColumnType("int");

                    b.Property<int>("Mileage")
                        .HasColumnType("int");

                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.Property<string>("Trim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VIN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("VehicleBasicIdentificationId");

                    b.HasIndex("BodyTypeId");

                    b.HasIndex("MakeId");

                    b.HasIndex("ModelId");

                    b.HasIndex("VehicleId")
                        .IsUnique();

                    b.ToTable("VehicleBasicIdentification");
                });

            modelBuilder.Entity("ZK.Domain.Entities.Vehicles.VehicleImage", b =>
                {
                    b.Property<int>("VehicleImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleImageId"));

                    b.Property<DateTime>("AddedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("ImageData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("VehicleImageId");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("VehicleImageId"));

                    b.HasIndex("VehicleId");

                    b.ToTable("VehicleImages", (string)null);
                });

            modelBuilder.Entity("ZK.Domain.Entities.Vehicles.VehicleMake", b =>
                {
                    b.Property<int>("VehicleMakeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleMakeId"));

                    b.Property<byte[]>("ImageData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("VehicleMakeId");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("VehicleMakeId"));

                    b.ToTable("VehicleMakes", (string)null);

                    b.HasData(
                        new
                        {
                            VehicleMakeId = 1,
                            ImageData = new byte[0],
                            Name = "Toyota"
                        },
                        new
                        {
                            VehicleMakeId = 2,
                            ImageData = new byte[0],
                            Name = "Ford"
                        },
                        new
                        {
                            VehicleMakeId = 3,
                            ImageData = new byte[0],
                            Name = "Honda"
                        },
                        new
                        {
                            VehicleMakeId = 4,
                            ImageData = new byte[0],
                            Name = "Chevrolet"
                        });
                });

            modelBuilder.Entity("ZK.Domain.Entities.Vehicles.VehicleModel", b =>
                {
                    b.Property<int>("VehicleModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleModelId"));

                    b.Property<int>("MakeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("VehicleModelId");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("VehicleModelId"));

                    b.HasIndex("MakeId");

                    b.ToTable("VehicleModels", (string)null);

                    b.HasData(
                        new
                        {
                            VehicleModelId = 1,
                            MakeId = 1,
                            Name = "Camry"
                        },
                        new
                        {
                            VehicleModelId = 2,
                            MakeId = 1,
                            Name = "Corolla"
                        },
                        new
                        {
                            VehicleModelId = 3,
                            MakeId = 1,
                            Name = "RAV4"
                        },
                        new
                        {
                            VehicleModelId = 4,
                            MakeId = 2,
                            Name = "F-150"
                        },
                        new
                        {
                            VehicleModelId = 5,
                            MakeId = 2,
                            Name = "Mustang"
                        },
                        new
                        {
                            VehicleModelId = 6,
                            MakeId = 3,
                            Name = "Civic"
                        },
                        new
                        {
                            VehicleModelId = 7,
                            MakeId = 3,
                            Name = "Accord"
                        },
                        new
                        {
                            VehicleModelId = 8,
                            MakeId = 4,
                            Name = "Silverado"
                        },
                        new
                        {
                            VehicleModelId = 9,
                            MakeId = 4,
                            Name = "Malibu"
                        });
                });

            modelBuilder.Entity("ZK.Domain.Entities.Vehicles.VehicleStatus", b =>
                {
                    b.Property<int>("VehicleStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleStatusId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("VehicleStatusId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("VehicleStatuses", (string)null);

                    b.HasData(
                        new
                        {
                            VehicleStatusId = 1,
                            Name = "On Sale"
                        },
                        new
                        {
                            VehicleStatusId = 2,
                            Name = "Sold"
                        },
                        new
                        {
                            VehicleStatusId = 3,
                            Name = "On Hold"
                        });
                });

            modelBuilder.Entity("ZK.Domain.Entities.Vehicles.VehicleTechnicalSpecification", b =>
                {
                    b.Property<int>("VehicleTechnicalSpecificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleTechnicalSpecificationId"));

                    b.Property<int>("DrivetrainId")
                        .HasColumnType("int");

                    b.Property<int>("EngineId")
                        .HasColumnType("int");

                    b.Property<int>("FuelTypeId")
                        .HasColumnType("int");

                    b.Property<int>("Horsepower")
                        .HasColumnType("int");

                    b.Property<int>("Kmpl_City")
                        .HasColumnType("int");

                    b.Property<int>("Kmpl_Combined")
                        .HasColumnType("int");

                    b.Property<int>("Kmpl_Highway")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfDoors")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfOwners")
                        .HasColumnType("int");

                    b.Property<int>("SeatingCapacity")
                        .HasColumnType("int");

                    b.Property<int>("Torque")
                        .HasColumnType("int");

                    b.Property<int>("TransmissionId")
                        .HasColumnType("int");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("VehicleTechnicalSpecificationId");

                    b.HasIndex("DrivetrainId");

                    b.HasIndex("EngineId");

                    b.HasIndex("FuelTypeId");

                    b.HasIndex("TransmissionId");

                    b.HasIndex("VehicleId")
                        .IsUnique();

                    b.ToTable("VehicleTechnicalSpecification");
                });

            modelBuilder.Entity("ZK.Domain.Entities.Sales.SaleHistory", b =>
                {
                    b.HasOne("ZK.Domain.Entities.Vehicles.Vehicle", "Vehicle")
                        .WithOne("SaleHistory")
                        .HasForeignKey("ZK.Domain.Entities.Sales.SaleHistory", "VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("ZK.Domain.Entities.Users.RoleClaim", b =>
                {
                    b.HasOne("ZK.Domain.Entities.Users.Role", "Role")
                        .WithMany("RoleClaims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ZK.Domain.Entities.Users.UserRole", b =>
                {
                    b.HasOne("ZK.Domain.Entities.Users.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZK.Domain.Entities.Users.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ZK.Domain.Entities.Vehicles.Vehicle", b =>
                {
                    b.HasOne("ZK.Domain.Entities.Vehicles.VehicleStatus", "VehicleStatus")
                        .WithMany("Vehicles")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("VehicleStatus");
                });

            modelBuilder.Entity("ZK.Domain.Entities.Vehicles.VehicleBasicIdentification", b =>
                {
                    b.HasOne("ZK.Domain.Entities.Vehicles.BodyType", "BodyType")
                        .WithMany("VehicleBasicIdentifications")
                        .HasForeignKey("BodyTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ZK.Domain.Entities.Vehicles.VehicleMake", "Make")
                        .WithMany("VehicleBasicIdentifications")
                        .HasForeignKey("MakeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ZK.Domain.Entities.Vehicles.VehicleModel", "Model")
                        .WithMany("VehicleBasicIdentifications")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ZK.Domain.Entities.Vehicles.Vehicle", "Vehicle")
                        .WithOne("VehicleBasicIdentification")
                        .HasForeignKey("ZK.Domain.Entities.Vehicles.VehicleBasicIdentification", "VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BodyType");

                    b.Navigation("Make");

                    b.Navigation("Model");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("ZK.Domain.Entities.Vehicles.VehicleImage", b =>
                {
                    b.HasOne("ZK.Domain.Entities.Vehicles.Vehicle", "Vehicle")
                        .WithMany("VehicleImages")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("ZK.Domain.Entities.Vehicles.VehicleModel", b =>
                {
                    b.HasOne("ZK.Domain.Entities.Vehicles.VehicleMake", "Make")
                        .WithMany("VehicleModels")
                        .HasForeignKey("MakeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Make");
                });

            modelBuilder.Entity("ZK.Domain.Entities.Vehicles.VehicleTechnicalSpecification", b =>
                {
                    b.HasOne("ZK.Domain.Entities.Vehicles.Drivetrain", "Drivetrain")
                        .WithMany("VehicleTechnicalSpecifications")
                        .HasForeignKey("DrivetrainId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ZK.Domain.Entities.Vehicles.Engine", "Engine")
                        .WithMany("VehicleTechnicalSpecifications")
                        .HasForeignKey("EngineId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ZK.Domain.Entities.Vehicles.FuelType", "FuelType")
                        .WithMany("VehicleTechnicalSpecifications")
                        .HasForeignKey("FuelTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ZK.Domain.Entities.Vehicles.Transmission", "Transmission")
                        .WithMany("VehicleTechnicalSpecifications")
                        .HasForeignKey("TransmissionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ZK.Domain.Entities.Vehicles.Vehicle", "Vehicle")
                        .WithOne("VehicleTechnicalSpecification")
                        .HasForeignKey("ZK.Domain.Entities.Vehicles.VehicleTechnicalSpecification", "VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drivetrain");

                    b.Navigation("Engine");

                    b.Navigation("FuelType");

                    b.Navigation("Transmission");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("ZK.Domain.Entities.Users.Role", b =>
                {
                    b.Navigation("RoleClaims");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ZK.Domain.Entities.Users.User", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ZK.Domain.Entities.Vehicles.BodyType", b =>
                {
                    b.Navigation("VehicleBasicIdentifications");
                });

            modelBuilder.Entity("ZK.Domain.Entities.Vehicles.Drivetrain", b =>
                {
                    b.Navigation("VehicleTechnicalSpecifications");
                });

            modelBuilder.Entity("ZK.Domain.Entities.Vehicles.Engine", b =>
                {
                    b.Navigation("VehicleTechnicalSpecifications");
                });

            modelBuilder.Entity("ZK.Domain.Entities.Vehicles.FuelType", b =>
                {
                    b.Navigation("VehicleTechnicalSpecifications");
                });

            modelBuilder.Entity("ZK.Domain.Entities.Vehicles.Transmission", b =>
                {
                    b.Navigation("VehicleTechnicalSpecifications");
                });

            modelBuilder.Entity("ZK.Domain.Entities.Vehicles.Vehicle", b =>
                {
                    b.Navigation("SaleHistory");

                    b.Navigation("VehicleBasicIdentification");

                    b.Navigation("VehicleImages");

                    b.Navigation("VehicleTechnicalSpecification");
                });

            modelBuilder.Entity("ZK.Domain.Entities.Vehicles.VehicleMake", b =>
                {
                    b.Navigation("VehicleBasicIdentifications");

                    b.Navigation("VehicleModels");
                });

            modelBuilder.Entity("ZK.Domain.Entities.Vehicles.VehicleModel", b =>
                {
                    b.Navigation("VehicleBasicIdentifications");
                });

            modelBuilder.Entity("ZK.Domain.Entities.Vehicles.VehicleStatus", b =>
                {
                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
